### ISSUE TITLE
Implement a CLI

### ISSUE THREAD

**Issue by ocefpaf** [rsignell-usgs/yaml2ncml#4]
@rsignell-usgs I like [docopt](http://docopt.org/) for implementing CLIs, do you have any objection?  It is not in the standard library, but it is easy to install (pure python).

If you vote yes can you help me to put together an interface?

**Comment by ocefpaf** [comment]
@rsignell-usgs 

Do you envision more options/switches for the command line call below?

```bash
yaml2ncml input.yaml output.ncml
```

**Comment by ocefpaf** [comment]
Maybe a  `-dry-run` to print the output.ncml instead of creating it?

**Comment by rsignell-usgs** [comment]
Well, there is really no harm in creating the ncml,  so -dry-run seems a bit unecessary, don't you think?
One thing that we should have in the future is  `--check ugrid`   `--check sgrid` or something

**Comment by ocefpaf** [comment]
> Well, there is really no harm in creating the ncml, so --dry-run seems a bit unecessary, don't you think?

I like to see things on the screen when debugging them.  Like when creating a new yaml file with the aggregation info.  Anyways, I already found a better way around it.  It will be up in a few moments...

> One thing that we should have in the future is --check ugrid --check sgrid or something that runs the resulting NcML through a compliance checker.

Very important indeed.  I will open a new issue with that so we do not get lost.

**Comment by rsignell-usgs** [comment]
Is the CLI version working?    I guess I don't know how to run it. 
I build a conda module
```
conda install -c rsignell yaml2ncml
```
but then don't know what do do.  :crying_cat_face:

**Comment by ocefpaf** [comment]
I said to wait for the next PRs...  I am still smoothing out some corners.  I have a prototype working here.

**Comment by ocefpaf** [comment]
PR #9 should add an executable `yaml2ncml` to your path.  So far I only test it by entering the `tests` directory and calling:

```bash
yaml2ncml roms.yaml --output test6.ncml
```

If you omit `--output test6.ncml` the ncml will be dumped in the screen.
